# frozen_string_literal: true

return if Rails.application.secrets.elections.blank?

Decidim::BulletinBoard.configure do |config|
  # Exposes a configuration option: the bulletin board server
  config.bulletin_board_server = Rails.application.secrets.elections[:bulletin_board_server]

  # Exposes a configuration option: the bulletin board public key
  config.bulletin_board_public_key = Rails.application.secrets.elections[:bulletin_board_public_key]

  # Exposes a configuration option: the api key generated by the Bulletin Board for the Decidim instance
  config.authority_api_key = Rails.application.secrets.elections[:authority_api_key]

  # Exposes a configuration option: the authority name String
  config.authority_name = Rails.application.secrets.elections[:authority_name]

  # Exposes a configuration option: private key, that got generated by the Decidim instance
  config.authority_private_key = Rails.application.secrets.elections[:authority_private_key]

  # Exposes a configuration option: the scheme name to be used for messages
  config.scheme_name = Rails.application.secrets.elections[:scheme_name]

  # Exposes a configuration option: the quorum
  config.quorum = Rails.application.secrets.elections[:quorum]

  # Exposes a configuration option: number of trustees for an election
  config.number_of_trustees = Rails.application.secrets.elections[:number_of_trustees]
end