= Proposals

In the proposals module we are providing a few mutations that we find useful for day-to-day management of Decidim instance outside the admin.

== User facing

* xref:develop:api/reference/components/proposals/create.adoc[Create Proposals]
* xref:develop:api/reference/components/proposals/update.adoc[Update Proposals]
* xref:develop:api/reference/components/proposals/withdraw.adoc[Withdraw Proposals]
* xref:develop:api/reference/components/proposals/vote.adoc[Vote Proposals]

== Admin facing

* xref:develop:api/reference/components/proposals/answer.adoc[Answer Proposals]

== Vote Proposals

To use the API to vote any proposal, you will need to use the following API request.

[source,graphql]
----
mutation {
  proposals {
    proposal(id: "123") {
      vote(input: {}) {
      }
    }
  }
}
----

=== Error Handling

When you are not authorized or when you are not authenticated, the server will respond with a simple:

[source,json]
----
{
  "errors": [
    {
      "message": "You do not have permission to perform this mutation",
      "locations": [{"line": 2, "column" : 3}],
      "path": ["vote"],
      "extensions": {
        "code": "MUTATION_NOT_AUTHORIZED"
      }
    }
  ],
  "data": {"vote": null}
}
----

Additionally when the proposal is already voted, or the votes are not enabled:

[source,json]
----
{
  "errors": [
    {
      "message": "There was a problem voting the proposal.",
      "locations": [{"line": 2, "column": 3}],
      "path": ["vote"],
      "extensions": {"code": "VALIDATION_ERROR"}
    }
  ],
  "data": {"vote": null}
}
----

== Unvote Proposals

To use the API to unvote any proposal, you will need to use the following API request.

[source,graphql]
----
mutation {
  proposals {
    proposal(id: "123") {
      unvote(input: {}) {
      }
    }
  }
}
----

=== Error Handling

When you are not authorized or when you are not authenticated, the server will respond with a simple:

[source,json]
----
{
  "errors":
    [
      {
        "message": "You do not have permission to perform this mutation",
        "locations": [
          {"line": 2, "column": 3}
        ],
        "path": ["unvote"],
        "extensions": {"code": "MUTATION_NOT_AUTHORIZED"}
      }
    ],
  "data": {"unvote": null}
}
----
