= Create Attachment Collections

==  Input attributes

When you want to create a Decidim attachment collection, you need to rely on the `AttachmentCollectionAttributes` type, which has the following input fields.

[source]
----
• description           (optional) - JSON
• key                   (optional) - String
• name                  (Required) - JSON
• weight                (Optional) - Integer
----

== Sample request

The `CreateAttachmentCollection` mutation allows authenticated administrators to create new attachment collections within certain resources. This mutation uses the existing `CreateAttachmentCollection` command from the admin controller. In the below  example, we are creating an attachment bound to a `Result` type.

[source,graphql]
----
mutation createAttachmentCollectionMutation($componentId: ID!, $resultId: ID!, $input: CreateAttachmentCollectionInput!) {
  component(id: $componentId) {
    ... on AccountabilityMutation {
      result(id: $resultId) {
        createAttachmentCollection(input: $input) {
          id
          name {
            translation(locale: "en")
          }
          description {
            translation(locale: "en")
          }
          weight
          key
        }
      }
    }
  }
}
----

Example of submitted variables

[source,json]
----
{
  "componentId": "3",
  "resultId": "5",
  "input": {
    "attributes": {
      "weight": 1,
      "name": {
        "en": "Your english name"
      },
      "description": {
        "en": "Your english description"
      }
    }
  }
}

----

== Error Handling

The most frequent errors that can be generated by this mutation are as follows:

* xref:develop:api/reference/errors/unauthorized_mutation.adoc[Unauthorized Mutation Error - MUTATION_NOT_AUTHORIZED_ERROR]
* xref:develop:api/reference/errors/invalid_locale_error.adoc[Invalid Locale Error - INVALID_LOCALE_ERROR]
* xref:develop:api/reference/errors/attribute_validation_error.adoc[Attribute Validation Error - ATTRIBUTE_VALIDATION_ERROR]
* xref:develop:api/reference/errors/unauthorized_object.adoc[Unauthorized Object Error - UNAUTHORIZED_OBJECT_ERROR]
