require 'decidim/extends/create_comment_extend.rb'
require 'decidim/extends/create_proposal_extend.rb'
require 'decidim/extends/commentable_extend.rb'
require 'decidim/extends/comment_extend.rb'
require 'decidim/extends/comment_created_event_extend.rb'
require 'decidim/extends/sorted_comments_extend.rb'
require 'decidim/extends/admin_ability_extend.rb'