= API file upload handling

In order to create attachments using the API, you need first to handle the file upload, and after that, you can create the attachment record.

The following snippet, will handle the file upload, returning you the uploaded blob together with its `signedId`.

[source,bash]
----
curl -X POST https://example.org/api/ \
  -F 'operations={"query":"mutation ($input: UploadFileInput!) { uploadFile(input: $input) { blob { id filename byteSize signedId checksum } } }","variables":{"input":{"file":null}}}' \
  -F 'map={"0":["variables.input.file"]}' \
  -F '0=@/path/to/file.jpg'
----

Having the `signedId`, you will be able to pass it as the `file.signedId` parameter for the createAttachment mutation, obtaining this way a new attachment record.

[source,json]
----
{
  "componentId": "3",
  "resultId": "5",
  "input": {
    "attributes": {
      "weight": 1,
      "title": {
        "en": "Your english title"
      },
      "description": {
        "en": "Your english description"
      },
      "file": {
        "signedId": "eyJfcmFpbHMiOnsiZGF0YSI6MzI1MjQsInB1ciI6IkFjdGl2ZVN0b3JhZ2U6OkJsb2IifX0=--3f8a2b1c9d0e4f5a6b7c8d9e0f1a2b3c4d5e6f7a" // The signedId obtained from file upload
      }
    }
  }
}

----

For additional details feel free to browse associated resources.

== Blobs (Handling Files)

* xref:develop:api/reference/uploads/blobs/upload.adoc[Upload files]
* xref:develop:api/reference/uploads/blobs/delete.adoc[Delete files]

== Attachments

* xref:develop:api/reference/uploads/attachments/create.adoc[Create Attachments]
* xref:develop:api/reference/uploads/attachments/update.adoc[Update Attachments]
* xref:develop:api/reference/uploads/attachments/delete.adoc[Delete Attachments]

== Attachment Collections

* xref:develop:api/reference/uploads/attachment_collections/create.adoc[Create Collections]
* xref:develop:api/reference/uploads/attachment_collections/update.adoc[Update Collections]
* xref:develop:api/reference/uploads/attachment_collections/delete.adoc[Delete Collections]
