configuration:
  - .github/**/*
  - /config/**/*
  - /*.json
  - /*.yml
  - /*.yaml
dependencies:
  - "*.gemspec"
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
javascript: "*.js"
"module: accountability": decidim-accountability/**/*
"module: admin": decidim-admin/**/*
"module: api": decidim-api/**/*
"module: assemblies": decidim-assemblies/**/*
"module: blogs": decidim-blogs/**/*
"module: budgets": decidim-budgets/**/*
"module: comments": decidim-comments/**/*
"module: conferences": decidim-conferences/**/*
"module: consultations": decidim-consultations/**/*
"module: core": decidim-core/**/*
"module: debates": decidim-debates/**/*
"module: design": decidim-design/**/*
"module: dev": decidim-dev/**/*
"module: elections": decidim-elections/**/*
"module: forms": decidim-forms/**/*
"module: generators": decidim-generators/**/*
"module: initiatives": decidim-initiatives/**/*
"module: meetings": decidim-meetings/**/*
"module: pages": decidim-pages/**/*
"module: participatory processes": decidim-participatory_processes/**/*
"module: proposals": decidim-proposals/**/*
"module: sortitions": decidim-sortitions/**/*
"module: surveys": decidim-surveys/**/*
"module: system": decidim-system/**/*
"module: templates": decidim-templates/**/*
"module: verifications": decidim-verifications/**/*
"team: documentation":
  - docs/**/*
  - /README.adoc
