# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # /Gemfile.lock
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 1
    ignore:
      - dependency-name: "rails"
        update-types: [ "version-update:semver-minor", "version-update:semver-major" ]
    groups:
      rails:
        patterns:
          - "rails*"
          - "actionpack"
          - "actioncable"
          - "actionmailbox"
          - "actionmailer"
          - "actiontext"
          - "actionview"
          - "activestorage"
          - "railties"
          - "activemodel"
          - "activejob"
          - "activerecord"
          - "activesupport"
      rspec:
        patterns:
          - "rspec-core"
          - "rspec-expectations"
          - "rspec-mocks"
          - "rspec-support"
    versioning-strategy: "increase"
    labels:
      - "dependencies"
      - "type: internal"
      - "configuration"
    commit-message:
      prefix: "Bump to dependencies"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/decidim-generators/lib/decidim/generators/component_templates/github"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
      - "type: internal"
      - "configuration"
    commit-message:
      prefix: "Bump to dependencies"
    groups:
      github-actions:
        patterns:
          - "*"

  # NPM packages
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
      - "type: internal"
      - "module: core"
      - "javascript"
    commit-message:
      prefix: "Bump to dependencies"

  # NPM packages - core
  - package-ecosystem: "npm"
    directory: "/packages/core"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
      - "type: internal"
      - "javascript"
      - "module: core"
      - "configuration"
    commit-message:
      prefix: "Bump to dependencies"

  # NPM packages - eslint-config
  - package-ecosystem: "npm"
    directory: "/packages/eslint-config"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
      - "type: internal"
      - "javascript"
    commit-message:
      prefix: "Bump to dependencies"

  # NPM packages - browserslist-config
  - package-ecosystem: "npm"
    directory: "/packages/browserslist-config"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
      - "type: internal"
      - "javascript"
    commit-message:
      prefix: "Bump to dependencies"

  # NPM packages - stylelint-config
  - package-ecosystem: "npm"
    directory: "/packages/stylelint-config"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
      - "type: internal"
      - "javascript"
    commit-message:
      prefix: "Bump to dependencies"

  # NPM packages - dev
  - package-ecosystem: "npm"
    directory: "/packages/dev"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
      - "type: internal"
      - "javascript"
      - "module: dev"
    commit-message:
      prefix: "Bump to dependencies"

  # NPM packages - prettier-config
  - package-ecosystem: "npm"
    directory: "/packages/prettier-config"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
      - "type: internal"
      - "javascript"
    commit-message:
      prefix: "Bump to dependencies"

  # NPM packages - webpacker
  - package-ecosystem: "npm"
    directory: "/packages/webpacker"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Europe/Madrid"
    open-pull-requests-limit: 1
    labels:
      - "dependencies"
      - "type: internal"
      - "javascript"
      - "configuration"
      - "module: dev"
    commit-message:
      prefix: "Bump to dependencies"
