---

version: "2"

checks:
  method-complexity:
    config:
      threshold: 9

plugins:
  bundler-audit:
    enabled: true

  csslint:
    enabled: true
    exclude_paths:
      - "decidim-core/app/assets/stylesheets/decidim/email.css"

  duplication:
    enabled: true

    config:
      languages:
        javascript:
          mass_threshold: 1000

        ruby:
          mass_threshold: 80

    exclude_fingerprints:
      - 3806e0c6847f506e683c8bc4133b22e5
      - ae2cee64fca2a95102d03e03b9ffb54f

    exclude_paths:
      - "decidim-*/spec/**/*"

  eslint:
    enabled: false

  fixme:
    enabled: true

    exclude_paths:
     - decidim-comments/app/assets/javascripts/decidim/comments/bundle.js.map
     - .rubocop.yml

  grep:
    enabled: true

    config:
      patterns:
        no-trailing-whitespace:
          pattern: \s*$
          annotation: "Don't leave trailing whitespace"
          severity: minor
          categories: Style

    exclude_paths:
      - "decidim-design/**/*"

  markdownlint:
    enabled: true

    exclude_paths:
      - docs/*
      - .github/*
      - CHANGELOG.md

  rubocop:
    enabled: true
    channel: rubocop-0-51

exclude_patterns:
  - "**/vendor/"
  - "decidim-comments/app/assets/javascripts/decidim/comments/bundle.js"
  - "node_modules/"
  - "development_app/"
  - "docker_development_app/"
  - "spec/decidim_dummy_app/"
  - "coverage/"
  - "webpack.report.html"
