
build:
  image: codegram/rails:2.3.1
  environment:
    - RAILS_ENV=test
    - DATABASE_HOST=localhost
    - DATABASE_USERNAME=postgres
    - DATABASE_PASSWORD=mysecretpassword
    - GEM_HOME=vendor/bundle
  commands:
    - cd $$GEM; export BUNDLE_GEMFILE="`pwd`/Gemfile"
    - bundle install --jobs=3 --retry=3
    - bundle exec rake
compose:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
cache:
  mount:
    - vendor/bundle

matrix:
  GEM:
    - .
    - decidim-admin
    - decidim-core
    - decidim-system
