build:
  image: codegram/rails:2.3.1
  environment:
    - RAILS_ENV=test
    - DATABASE_HOST=localhost
    - DATABASE_USERNAME=postgres
    - DATABASE_PASSWORD=mysecretpassword
    - GEM_HOME=vendor/bundle
  commands:
    - bundle install
    - bundle exec rake
    - bundle exec rspec
compose:
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
cache:
  mount:
    - vendor/bundle
    - public/assets
