---

linters:
  ExtraNewline:
    enabled: true

  FinalNewline:
    enabled: true

  RequireInputAutocomplete:
    enabled: false

  SpaceAroundErbTag:
    enabled: true

  AllowedScriptType:
    enabled: true
    allowed_types:
      - text/javascript
      - text/template

  Rubocop:
    enabled: true

    rubocop_config:
      inherit_from:
        - .rubocop.yml

      AllCops:
        DisabledByDefault: true

      Style/Copyright:
        Enabled: false

      Style/FrozenStringLiteralComment:
        Enabled: false

      Style/StringLiterals:
        EnforcedStyle: double_quotes

      Layout/LineLength:
        Enabled: false

      Layout/FirstArgumentIndentation:
        Enabled: false

      Layout/SpaceInsideHashLiteralBraces:
        Enabled: true

      Layout/BlockAlignment:
        Enabled: false

      Layout/MultilineMethodCallBraceLayout:
        Enabled: false

      Layout/FirstArrayElementIndentation:
        Enabled: false

      Layout/TrailingEmptyLines:
        Enabled: false

      Naming/FileName:
        Enabled: false

      Rails/LinkToBlank:
        Enabled: false

      Naming/VariableName:
        Enabled: false

      Layout/MultilineMethodCallIndentation:
        Enabled: false

      Layout/IndentationWidth:
        Enabled: false

      Layout/MultilineAssignmentLayout:
        Enabled: false
