---

linters:
  ExtraNewline:
    enabled: true

  FinalNewline:
    enabled: true

  SpaceAroundErbTag:
    enabled: true

  AllowedScriptType:
    enabled: true
    allowed_types:
      - text/javascript
      - text/template

  Rubocop:
    enabled: true

    rubocop_config:
      AllCops:
        DisabledByDefault: true

      Style/StringLiterals:
        EnforcedStyle: double_quotes

      Layout/SpaceInsideHashLiteralBraces:
        Enabled: true
