image:
  file: .gitpod.Dockerfile

tasks:
  - name: Development app
    init: |
      (
        [ $(sudo pg_lsclusters -h | wc -l) -eq 0 ] && (
          sudo mkdir -p /workspace/postgresql/data /workspace/etc/postgresql &&
          sudo chown -R postgres:postgres /workspace/postgresql /workspace/etc/postgresql &&
          sudo pg_createcluster -d /workspace/postgresql/data $PGVERSION main
        ) || echo "Database exists"
      ) &&
      sudo service postgresql start &&
      (
        [ $(sudo su postgres -c "psql -At -c \"SELECT COUNT(usename) FROM pg_user WHERE usename = '${DATABASE_USERNAME}'\"") -eq 0 ] && (
          sudo su postgres -c "psql -c 'CREATE USER $DATABASE_USERNAME SUPERUSER'" &&
          sudo su postgres -c "psql -c \"ALTER ROLE $DATABASE_USERNAME WITH PASSWORD '${DATABASE_PASSWORD}'\""
        ) || echo "Database user exists"
      ) &&
      mkdir -p .vscode &&
      echo '{"workbench.startupEditor": "none"}' > .vscode/settings.json &&
      echo 'RAILS_DEVELOPMENT_HOST=3000-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}' > .rbenv-vars &&
      bundle install --jobs 4 &&
      bundle exec rake development_app &&
      echo 'Rails.application.config.hosts << ENV.fetch("RAILS_DEVELOPMENT_HOST", "")' > development_app/config/initializers/gitpod.rb &&
      cd development_app &&
      echo "Compiling assets, please wait a moment..." &&
      ./bin/webpacker
    command: |
      sudo service postgresql start &&
      cd development_app &&
      ./bin/rails runner 'Decidim::Organization.first.update!(host: ENV.fetch("RAILS_DEVELOPMENT_HOST", "localhost"))' &&
      (sleep 10 && gp preview $(gp url 3000) --external &) &&
      ./bin/rails s -b 0.0.0.0

ports:
  - name: Web App
    description: The main application web server
    port: 3000
    onOpen: open-preview
    visibility: public
  - name: Webpacker
    description: The webpacker dev server for asset reloading
    port: 3035
    onOpen: ignore
    visibility: public
  - name: Database
    description: PostgreSQL database server
    port: 5432
    onOpen: ignore
    visibility: private
