image:
  file: .gitpod.Dockerfile

tasks:
  - name: Prepare development app
    init: |
      sudo service postgresql start &&
      mkdir -p .vscode &&
      echo '{"workbench.startupEditor": "none"}' > .vscode/settings.json &&
      echo 'RAILS_DEVELOPMENT_HOST="3000-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"' > .rbenv-vars &&
      bundle &&
      bundle exec rake development_app &&
      echo 'Rails.application.config.hosts << ENV.fetch("RAILS_DEVELOPMENT_HOST", "").gsub(/\A"|"\Z/, "")' > development_app/config/initializers/gitpod.rb &&
      echo "Compiling assets, please wait a moment..." &&
      ./bin/webpacker &&
      gp sync-done dev-app-ready &&
      exit
  - name: Development server
    command: |
      gp sync-await dev-app-ready &&
      cd development_app &&
      ./bin/rails runner 'Decidim::Organization.first.update!(host: ENV.fetch("RAILS_DEVELOPMENT_HOST", "localhost").gsub(/\A"|"\Z/, ""))' &&
      (sleep 10 && gp preview $(gp url 3000) --external &) &&
      ./bin/rails s
    openMode: split-right

ports:
  - name: Web App
    description: The main application web server
    port: 3000
    onOpen: open-preview
    visibility: public
  - name: Webpacker
    description: The webpacker dev server for asset reloading
    port: 3035
    onOpen: ignore
    visibility: public
  - name: Database
    description: PostgreSQL database server
    port: 5432
    onOpen: ignore
    visibility: private
