image:
  file: .gitpod.Dockerfile

tasks:
  - name: Development app
    init: |
      sudo service postgresql start &&
      echo 'RAILS_DEVELOPMENT_HOSTS="3000-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"' > .rbenv-vars &&
      bundle &&
      bundle exec rake development_app &&
      echo 'Rails.application.config.hosts << ENV.fetch("RAILS_DEVELOPMENT_HOSTS", "")' > development_app/config/initializers/gitpod.rb
    command: |
      cd development_app &&
      ./bin/rails runner 'Decidim::Organization.first.update!(host: ENV.fetch("RAILS_DEVELOPMENT_HOSTS", "localhost"))' &&
      ./bin/dev

ports:
  - port: 5432
    onOpen: ignore
    visibility: private
  - port: 3000
    onOpen: open-browser
