Rails/DurationArithmetic:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Lint/SymbolConversion:
  Enabled: false

Lint/EmptyClass:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

Lint/NoReturnInBeginEndBlocks:
  Enabled: false

Lint/RedundantCopDisableDirective:
  Enabled: false

Style/HashConversion:
  Enabled: false

Style/QuotedSymbols:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Security/IoMethods:
  Enabled: false

Rails/CompactBlank:
  Enabled: false

Security/Open:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Rails/EagerEvaluationLogMessage:
  Enabled: false

Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Lint/UnmodifiedReduceAccumulator:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Rails/DuplicateScope:
  Enabled: false

Rails/ExpandedDateRange:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

RSpec/VerifiedDoubleReference:
  Enabled: false

Rails/TransactionExitStatement:
  Enabled: false
