RSpec/ExcessiveDocstringSpacing:
  Enabled: false

RSpec/StubbedMock:
  Enabled: false

Rails/DurationArithmetic:
  Enabled: false

RSpec/FactoryBot/SyntaxMethods:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Lint/SymbolConversion:
  Enabled: false

Lint/EmptyClass:
  Enabled: false

Lint/RedundantSafeNavigation:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

Lint/NoReturnInBeginEndBlocks:
  Enabled: false

Lint/RedundantCopDisableDirective:
  Enabled: false

Style/RedundantArgument:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/MapToHash:
  Enabled: false

Style/HashConversion:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/QuotedSymbols:
  Enabled: false

Style/FetchEnvVar:
  Enabled: false

Style/RedundantParentheses:
  Enabled: false

Style/DocumentDynamicEvalDefinition:
  Enabled: false

Style/ClassEqualityComparison:
  Enabled: false

Style/NegatedIfElseCondition:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Security/IoMethods:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: false

Layout/LineEndStringConcatenationIndentation:
  Enabled: false

Rails/CompactBlank:
  Enabled: false

Security/Open:
  Enabled: false

Lint/DuplicateBranch:
  Enabled: false

Layout/LeadingCommentSpace:
  Enabled: false

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Rails/EagerEvaluationLogMessage:
  Enabled: false

Style/FileWrite:
  Enabled: false
  
Rails/RedundantPresenceValidationOnBelongsTo:
  Enabled: false

Rails/HasManyOrHasOneDependent:
  Enabled: false

Lint/UnmodifiedReduceAccumulator:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Style/SelectByRegexp:
  Enabled: false

Rails/DuplicateScope:
  Enabled: false

RSpec/IdenticalEqualityAssertion:
  Enabled: false

Style/StringChars:
  Enabled: false

Rails/ExpandedDateRange:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

RSpec/VerifiedDoubleReference:
  Enabled: false

Rails/TransactionExitStatement:
  Enabled: false
