inherit_from: .rubocop_todo.yml

inherit_gem:
  decidim-dev: rubocop-decidim.yml

inherit_mode:
  merge:
    - Exclude

Style/SafeNavigationChainLength:
  Exclude:
    - decidim-verifications/db/migrate/20171030133426_move_authorizations_to_new_api.rb
    - decidim-accountability/app/forms/decidim/accountability/admin/result_form.rb
    - decidim-core/app/helpers/decidim/newsletters_helper.rb
    - decidim-core/app/models/decidim/attachment.rb
    - decidim-proposals/app/cells/decidim/proposals/proposals_picker_cell.rb
    - decidim-proposals/spec/types/integration_schema_spec.rb
    - decidim-admin/app/views/decidim/admin/taxonomy_filters/new.html.erb

