Naming/VariableNumber:
  Enabled: false

Style/HashConversion:
  Enabled: false

Style/QuotedSymbols:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Security/IoMethods:
  Enabled: false

Security/Open:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

RSpec/VerifiedDoubleReference:
  Enabled: false

