---

Rails:
  Enabled: true

Rails/ActionFilter:
  Include:
    - decidim-*/app/controllers/**/*.rb

Rails/CreateTableWithTimestamps:
  Enabled: false

Rails/EnumUniqueness:
  Include:
    - decidim-*/app/models/**/*.rb

Rails/Exit:
  Include:
    - decidim-*/app/**/*.rb
    - decidim-*/config/**/*.rb
    - decidim-*/lib/**/*.rb
  Exclude:
    - decidim-*/lib/**/*.rake

Rails/FindBy:
  Include:
    - "**/*.rb"

Rails/FindEach:
  Include:
    - decidim-*/app/models/**/*.rb

Rails/HasAndBelongsToMany:
  Include:
    - decidim-*/app/models/**/*.rb

Rails/HasManyOrHasOneDependent:
  Include:
    - decidim-*/app/models/**/*.rb

Rails/InverseOf:
  Enabled: false

Rails/LexicallyScopedActionFilter:
  Include:
    - decidim-*/app/controllers/**/*.rb

Rails/NotNullColumn:
  Enabled: false

Rails/Output:
  Include:
    - decidim-*/app/**/*.rb
    - decidim-*/config/**/*.rb
    - decidim-*/db/**/*.rb
    - decidim-*/lib/**/*.rb
  Exclude:
    - decidim-core/db/seeds.rb
    - decidim-core/lib/decidim/component_manifest.rb
    - decidim-core/lib/decidim/participatory_space_manifest.rb
    - decidim-system/db/seeds.rb

Rails/OutputSafety:
  Enabled: false

Rails/ReadWriteAttribute:
  Include:
    - decidim-*/app/models/**/*.rb

Rails/ReversibleMigration:
  Enabled: false

Rails/ScopeArgs:
  Include:
    - decidim-*/app/models/**/*.rb

Rails/SkipsModelValidations:
  Enabled: true

Rails/Validation:
  Include:
    - decidim-*/app/models/**/*.rb
