codecov:
  branch: master
  bot: null
  notify:
    after_n_builds: 

coverage:
  precision: 2
  round: down
  range: "70...100"

  notify:
    slack:
      default:
        url: null
        threshold: null
        branches: null
        attachments: "sunburst, diff"

    hipchat:
      default:
        url: null
        notify: no
        threshold: null
        branches: null
        card: yes
        only_pulls: null
        message: null

    gitter:
      default:
        url: null
        threshold: null
        branches: null
        message: null

    webhook:
      default:
        url: null
        threshold: null
        branches: null
        only_pulls: null

    irc:
      default:
        server: null
        channel: null
        branches: null
        threshold: null
        message: null

  status:
    project:
      default:
        base: pr
        target: auto
        threshold: 0.5%
        branches: null

    patch:
      default:
        only_pulls: true
        base: pr
        target: auto
        target: 50%
        branches: null

    changes:
      default:
        branches: null

  ignore:
  - "decidim-*/spec/*"
  - "spec/*"
  - "decidim-*/lib/**/*/test/*"
  - "lib/**/*/test/*"
  - "bundle.js"
  - "vendor/*"
  - "node_modules/*"
  - ".bundle/*"

comment:
  layout: "header, diff, changes, sunburst, uncovered, tree"
  branches: null
  behavior: default
