comment: false
ignore:
  - "**/engine.rb"
  - "**/admin-engine.rb"
  - "**/component.rb"
  - "**/participatory_space.rb"
coverage:
  status:
    patch: false
    project:
      default:
        threshold: 0.1%
github_checks:
  annotations: false
flag_management:
  default_rules:
    carryforward: true
