comment: false
ignore:
  - "decidim-*/lib/decidim/**/engine.rb"
  - "decidim-*/lib/decidim/**/admin-engine.rb"
  - "decidim-*/lib/decidim/**/component.rb"
  - "decidim-*/lib/decidim/**/participatory_space.rb"
coverage:
  status:
    project:
      default: false
      develop:
        threshold: 0.1%
        flag_coverage_not_uploaded_behavior: exclude
        flags:
          - decidim-accountability
          - decidim-admin
          - decidim-api
          - decidim-assemblies
          - decidim-blogs
          - decidim-budgets
          - decidim-comments
          - decidim-conferences
          - decidim-consultations
          - decidim-core
          - decidim-debates
          - decidim-elections
          - decidim-forms
          - decidim-generators
          - decidim-initiatives
          - decidim-meetings
          - decidim-pages
          - decidim-participatory_processes
          - decidim-proposals
          - decidim-sortitions
          - decidim-surveys
          - decidim-system
          - decidim-templates
          - decidim-verifications
github_checks:
  annotations: false
