---

coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    project: true

    patch:
      default:
        target: 50%

    changes: false

comment:
  layout: "header, diff"
  behavior: default
