---

coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    project:
      default:
        threshold: 1%

    patch:
      default:
        target: 50%

    changes: false

comment:
  layout: "header, diff"
  behavior: default

ignore:
  - package-lock.json
  - *.md
