---

coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    project:
      default:
        threshold: 1%
      core:
        threshold: 1%
        flags: core
      assemblies:
        threshold: 1%
        flags: assemblies
      api:
        threshold: 1%
        flags: api
      processes:
        threshold: 1%
        flags: processes
      admin:
        threshold: 1%
        flags: admin
      system:
        threshold: 1%
        flags: system
      proposals:
        threshold: 1%
        flags: proposals
      comments:
        threshold: 1%
        flags: comments
      meetings:
        threshold: 1%
        flags: meetings
      pages:
        threshold: 1%
        flags: pages
      accountability:
        threshold: 1%
        flags: accountability
      budgets:
        threshold: 1%
        flags: budgets
      surveys:
        threshold: 1%
        flags: surveys

    patch:
      default:
        target: 50%

    changes: false

comment:
  layout: "header, diff"
  behavior: default

ignore:
  - package-lock.json
  - *.md

flags:
  core:
    paths:
      - decidim-core/
  assemblies:
    paths:
      - decidim-assemblies/
  api:
    paths:
      - decidim-api/
  processes:
    paths:
      - decidim-participatory_processes/
  admin:
    paths:
      - decidim-admin/
  system:
    paths:
      - decidim-system/
  proposals:
    paths:
      - decidim-proposals/
  comments:
    paths:
      - decidim-comments/
  meetings:
    paths:
      - decidim-meetings/
  pages:
    paths:
      - decidim-pages/
  accountability:
    paths:
      - decidim-accountability/
  budgets:
    paths:
      - decidim-budgets/
  surveys:
    paths:
      - decidim-surveys/
