= How to contribute to Decidim

We're really glad you're reading this, because we need volunteer developers to help this project come to fruition.

If you haven't already, come find us in https://gitter.im/decidim/decidim[Gitter].
We want you working on things you're excited about.

== Did you find a bug?

* *Do not open up a GitHub issue if the bug is a security vulnerability in Decidim*, and instead send us an email to security [at] decidim.org.
See xref:SECURITY.adoc[full security policy].
* *Ensure the bug was not already reported* by searching on GitHub under https://github.com/decidim/decidim/issues[Issues] and on https://meta.decidim.org/processes/bug-report/f/210/proposals[Metadecidim].
* If you're unable to find an open issue addressing the problem, https://meta.decidim.org/processes/bug-report/f/210/proposals/new[open a new one on Metadecidim].
Be sure to include a *title and clear description*, as much relevant information as possible, and a *code sample* or an *executable test case* demonstrating the expected behavior that is not occurring.

== Did you write a patch that fixes a bug or contributes features?

* Open a new GitHub pull request with the patch.
* Ensure the PR description clearly describes the problem and solution.
Include the relevant issue number if applicable.
* Check our https://github.com/decidim/decidim/blob/develop/docs/development_guide.md[development_guide]
* When the PR includes a breaking change or includes something that requires manual intervention when deploying, it's necessary to add it on the changelog upgrade notes.
See https://github.com/decidim/decidim/issues/5908[the discussion] regarding changelog simplification for further context.

== Do you intend to add a new feature or change an existing one?

* Suggest your change in https://meta.decidim.barcelona/processes/roadmap[Metadecidim] and start writing code.
* Do not open an issue on GitHub until you have collected positive feedback about the change.
GitHub issues are primarily intended for bug reports, fixes and already discussed features on https://meta.decidim.barcelona/processes/roadmap[Metadecidim].

== Do you have questions about the source code?

* Ask any question about how to use Decidim in https://gitter.im/decidim/decidim[Gitter].

== Do you want to contribute to Decidim documentation?

* Watch out the https://github.com/decidim/docs.decidim.org[Decidim Documentation repository] and the https://github.com/decidim/decidim.org[decidim.org] code website.

== Do you want to contribute to Decidim design?

* Go to the https://github.com/decidim/decidim/tree/master/decidim_app-design[Decidim design folder] and propose the changes that you want.

== Do you want to improve or add a new language for Decidim?

* Add a new issue asking for adding a user to the Crowdin project (https://github.com/decidim/decidim/issues/2073[example issue]).

Thanks!
:heart: :heart: :heart:

Decidim Team
