files:
  - source: /**/locales/en.yml
    translation: /**/locales/%locale%.yml
    languages_mapping:
      locale:
        ar: ar
        bg: bg
        ca: ca
        cs: cs
        da: da
        de: de
        el: el
        eo: eo
        es-ES: es
        es-MX: es-MX
        es-PY: es-PY
        et: et
        eu: eu
        fi: fi
        fi-plain: fi-plain
        fr: fr
        fr-CA: fr-CA
        ga: ga
        gl: gl
        hr: hr
        hu: hu
        id-ID: id
        is-IS: is
        it: it
        ja: ja
        ko: ko
        lt: lt
        lv: lv
        mt: mt
        nl: nl
        no: no
        pl: pl
        pt-BR: pt-BR
        pt-PT: pt
        ro-RO: ro
        rumany: ru
        sk: sk
        sl: sl
        sr: sr
        sv-SE: sv
        tr-TR: tr
        ukmany: uk
        vi: vi
        zh-CN: zh-CN
        zh-TW: zh-TW
