files:
  - source: /**/locales/en.yml
    translation: /**/locales/%locale%.yml
    languages_mapping:
      locale:
        ca: ca
        de: de
        es-ES: es
        es-PY: es-PY
        eu: eu
        fi: fi
        fr: fr
        gl: gl
        hu: hu
        id-ID: id
        it: it
        nl: nl
        pl: pl
        pt-BR: pt-BR
        pt-PT: pt
        rumany: ru
        sv-SE: sv
        tr-TR: tr
        ukmany: uk
