files:
  - source: /**/locales/en.yml
    translation: /**/locales/%locale%.yml
    languages_mapping:
      locale:
        ar: ar
        ca: ca
        cs: cs
        de: de
        el: el
        es-ES: es
        es-MX: es-MX
        es-PY: es-PY
        eu: eu
        fi: fi
        fi-plain: fi-plain
        fr: fr
        gl: gl
        hu: hu
        id-ID: id
        it: it
        nl: nl
        no: no
        pl: pl
        pt-BR: pt-BR
        pt-PT: pt
        ro-RO: ro
        rumany: ru
        sk: sk
        sv-SE: sv
        tr-TR: tr
        ukmany: uk
