FROM decidim/decidim:latest
LABEL maintainer="info@codegram.com"

ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV RAILS_ENV prod
ENV PORT 3000
ENV SECRET_KEY_BASE=no_need_for_such_secrecy
ENV RAILS_SERVE_STATIC_FILES=true

WORKDIR /code
COPY . .
WORKDIR /code/decidim_app-design

RUN bundle install
RUN rails assets:precompile
CMD rails s -p $PORT
