image::https://cdn.rawgit.com/decidim/decidim/develop/logo.svg[Decidim Logo,400]

The participatory democracy framework.

____
Free Open-Source participatory democracy, citizen participation and open government for cities and organizations
____

https://decidim.org[Decidim] is a participatory democracy framework, written in Ruby on Rails, originally developed for the Barcelona City government online and offline participation website.
Installing these libraries will provide you a generator and gems to help you develop web applications like the ones found on <<example-applications,example applications>> or like https://try.decidim.org[our demo application].

All members of the Decidim community agree with http://www.decidim.org/contract/[Decidim Social Contract or Code of Democratic Guarantees].

'''

image:https://img.shields.io/gem/v/decidim.svg[Gem,link=https://rubygems.org/gems/decidim] image:https://img.shields.io/gem/dt/decidim.svg[Gem,link=https://rubygems.org/gems/decidim] image:https://img.shields.io/github/contributors/decidim/decidim.svg[GitHub contributors,link=https://github.com/decidim/decidim/graphs/contributors] image:http://img.shields.io/badge/yard-docs-blue.svg[Yard Docs,link=http://rubydoc.info/github/decidim/decidim/master] image:https://img.shields.io/matrix/decidimdevs:matrix.org[Matrix,link=https://matrix.to/#/#decidimdevs:matrix.org]

Code quality

image:https://codecov.io/gh/decidim/decidim/branch/develop/graph/badge.svg[codecov,link=https://codecov.io/gh/decidim/decidim] image:https://api.codeclimate.com/v1/badges/ad8fa445086e491486b6/maintainability[Maintainability,link=https://codeclimate.com/github/decidim/decidim/maintainability] image:https://d322cqt584bo4o.cloudfront.net/decidim/localized.svg[Crowdin,link=https://crowdin.com/project/decidim]

= What do you need to do?

- https://docs.decidim.org/[Official Documentation]
- <<getting-started-with-decidim,Getting started with Decidim>>
- <<how-to-contribute,Contribute to the project>>
- <<modules,Modules>>
- <<browse-decidim,Create & browse development app>>

'''

== Getting started with Decidim

TLDR: install gem, generate a Ruby on Rails app, enjoy.

[source,console]
----
gem install decidim
decidim decidim_application
----

We've set up a guide on how to install, set up and upgrade Decidim.
See the https://docs.decidim.org/en/install/[Getting started guide].

== How to contribute

See xref:CONTRIBUTING.adoc[Contributing].

== Modules

If you need to have some features that we don't have yet, we recommend that you make a module.
This is a Ruby on Rails engine with some APIs specific to Decidim (for registering with the menus, integration with spaces like Participatory Processes or Assemblies, with /admin or /api, etc).

As a base you can use these modules, although check first that the version is compatible with your current Decidim version.
Also, you should know that until v1.0.0 We're under development, and these internal APIs can change.

We recommend that you extensively test your module.

See https://decidim.org/modules[Modules page on Decidim.org].

=== Authorizations Strategies

One specific thing regarding these kind of applications is the authorization or verification logic. This tries to solve the problem of how to verify that the user is who they say they are and that they have the right to participate in this city or organization. Read more about https://docs.decidim.org/en/customize/authorizations/[Authorizations] in our documentation.

== Following our license

If you plan to put your application in production, you'll need to publish it using the same license: GPL Affero 3.

We recommend doing that on GitHub (or any other code hosting platform) before publishing.

You can read more on "http://producingoss.com/en/governments-and-open-source.html#starting-open-for-govs[Being Open Source From Day One is Especially Important for Government Projects]".

If you have any trouble you can contact us on https://app.element.io/#/room/#decidimdevs:matrix.org[our Matrix.org chat room for developers].

== Example applications

Since Decidim is a ruby gem, you can check out the https://github.com/decidim/decidim/network/dependents?type=application[dependent repositories] to see how many applications are on the wild or tests that other developers have made. You can see a highlight of https://docs.decidim.org/en/develop/guide_example_apps/[example applications] in our documentation.

== Security

Security is very important to us.
If you have any issue regarding security, please disclose the information responsibly by sending an email to security [at] decidim [dot] org and not by creating a github/metadecidim issue.
We appreciate your effort to make Decidim more secure.
See xref:SECURITY.adoc[full security policy].

== Donations

If you want to support the project, consider making a donation through our https://opencollective.com/decidim[OpenCollective profile].
