# frozen_string_literal: true
require "decidim/core/test/shared_examples/authorable"
require "decidim/core/test/shared_examples/localised_email"
require "decidim/core/test/shared_examples/has_attachments"
require "decidim/core/test/shared_examples/has_feature"
require "decidim/core/test/shared_examples/has_scope"
require "decidim/core/test/shared_examples/has_category"
require "decidim/core/test/shared_examples/has_reference"
require "decidim/core/test/shared_examples/comments_examples"
require "decidim/core/test/shared_examples/reports_examples"
