# frozen_string_literal: true

require "decidim/core/test/shared_examples/authorable"
require "decidim/core/test/shared_examples/publicable"
require "decidim/core/test/shared_examples/localised_email"
require "decidim/core/test/shared_examples/has_attachments"
require "decidim/core/test/shared_examples/has_feature"
require "decidim/core/test/shared_examples/has_scope"
require "decidim/core/test/shared_examples/has_category"
require "decidim/core/test/shared_examples/has_reference"
require "decidim/core/test/shared_examples/comments_examples"
require "decidim/core/test/shared_examples/announcements_examples"
require "decidim/core/test/shared_examples/process_announcements_examples"
require "decidim/core/test/shared_examples/reportable"
require "decidim/core/test/shared_examples/reports_examples"
require "decidim/core/test/shared_examples/manage_moderations_examples"
require "decidim/core/test/shared_examples/paginated_resource_examples"
require "decidim/core/test/shared_examples/errors"
require "decidim/core/test/shared_examples/scope_helper_examples"
require "decidim/core/test/shared_examples/user_localised_email_examples"
require "decidim/core/test/shared_examples/follows_examples"
