# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

default: &default
  omniauth:
    facebook:
      app_id: <%= ENV["OMNIAUTH_FACEBOOK_APP_ID"] %>
      app_secret: <%= ENV["OMNIAUTH_FACEBOOK_APP_SECRET"] %>

development:
  <<: *default
  secret_key_base: f0be50b402c0828c949095c61fdf23807ae914a9509e200f4cf562e3ad4493518a4d96211b91dccfef8f20b80db473418f709932d8b479dab579af4101a7efb8

test:
  <<: *default
  secret_key_base: 42227b9e95c170e9438c2f4276c48499525121fc27f90be6bc992c43aab5425bdcef7763a7d890448bcb9dee31f6eb6637b4ecb18a2e7ae015666d82cb418a78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
