import 'foundation-sites'

// TODO-blat: old foundation imports, is necessary to import just those?
// import 'foundation.core'
// import 'foundation.util.box'
// import 'foundation.util.imageLoader'
// import 'foundation.util.keyboard'
// import 'foundation.util.mediaQuery'
// import 'foundation.util.motion'
// import 'foundation.util.nest'
// import 'foundation.util.timer'
// import 'foundation.util.touch'
// import 'foundation.util.triggers'
// import 'foundation.abide'
// import 'foundation.accordion'
// import 'foundation.accordionMenu'
// import 'foundation.drilldown'
// import 'foundation.dropdown'
// import 'foundation.dropdownMenu'
// import 'foundation.equalizer'
// import 'foundation.interchange'
// import 'foundation.magellan'
// import 'foundation.offcanvas'
// import 'foundation.responsiveMenu'
// import 'foundation.responsiveToggle'
// import 'foundation.reveal'
// import 'foundation.sticky'
// import 'foundation.tabs'
// import 'foundation.toggler'
// import 'foundation.tooltip'
// import 'foundation.responsiveAccordionTabs'
