# frozen_string_literal: true

source "https://rubygems.org"

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem "decidim", path: ".."
gem "puma", "~> 3.7"
gem "uglifier", ">= 1.3.0"
gem "faker"

group :development do
  gem "decidim-dev", path: ".."
  gem "listen", ">= 3.0.5", "< 3.2"
  gem "spring-watcher-listen", "~> 2.0.0"
end

gem "byebug"
