# frozen_string_literal: true

require "decidim/admin/test/manage_attachments_examples"
require "decidim/admin/test/manage_attachment_collections_examples"
require "decidim/admin/test/manage_component_permissions_examples"
require "decidim/admin/test/manage_moderations_examples"
require "decidim/admin/test/manage_taxonomy_filters_examples"
require "decidim/admin/test/manage_paginated_collection_examples"
require "decidim/admin/test/manage_participatory_space_publications_examples"
require "decidim/admin/test/manage_resource_soft_deletion_examples"
require "decidim/admin/test/filterable_examples"
require "decidim/admin/test/filters_participatory_space_users_examples"
require "decidim/admin/test/filters_participatory_space_user_roles_examples"
require "decidim/admin/test/manage_hide_content_examples"
require "decidim/admin/test/needs_admin_tos_accepted_examples"
require "decidim/admin/test/destroy_admin_examples"
require "decidim/admin/test/commands/publish_participatory_space_examples"
require "decidim/admin/test/invite_participatory_space_users_shared_context"
require "decidim/admin/test/taxonomy_filters_examples"
