import "src/decidim/meetings/admin/agendas"
import "src/decidim/meetings/admin/destroy_meeting_alert"
import "src/decidim/meetings/admin/meetings_form"
import "src/decidim/meetings/admin/registrations_form"
import "src/decidim/meetings/admin/registrations_invite_form"
