= Update Attachments

==  Input attributes

When you want to update a Decidim attachment's details, you need to rely on the `AttachmentAttributes` type, which has the following input fields.

[source]
----
• collection            (optional) - Integer
• description           (optional) - JSON
• file                  (Required) - JSON - FileInputObject format
• title                 (Required) - JSON
• weight                (Optional) - Integer
----

== Sample request

The `UpdateAttachment` mutation allows authenticated administrators to update attachments within certain resources. This mutation uses the existing `UpdateAttachment` command from the admin controller. In the below example, we are updating an attachment bound to a `Result` type.

[source,graphql]
----
mutation updateAttachmentMutation($componentId: ID!, $resultId: ID!, $input: UpdateAttachmentInput!) {
  component(id: $componentId) {
    ... on AccountabilityMutation {
      result(id: $resultId) {
        updateAttachment(input: $input) {
          id
          title {
            translation(locale: "en")
          }
          description {
            translation(locale: "en")
          }
        }
      }
    }
  }
}
----

Example of submitted variables

[source,json]
----
{
  "componentId": "3",
  "resultId": "5",
  "input": {
    "id":  "1234",
    "attributes": {
      "weight": 1,
      "title": {
        "en": "Your english name"
      },
      "description": {
        "en": "Your english description"
      },
      "file": {
        "blobId": 32524
      }
    }
  }
}

----

== Error Handling

The most frequent errors that can be generated by this mutation are as follows:

* xref:develop:api/reference/errors/unauthorized_mutation.adoc[Unauthorized Mutation Error - MUTATION_NOT_AUTHORIZED_ERROR]
* xref:develop:api/reference/errors/invalid_locale_error.adoc[Invalid Locale Error - INVALID_LOCALE_ERROR]
* xref:develop:api/reference/errors/attribute_validation_error.adoc[Attribute Validation Error - ATTRIBUTE_VALIDATION_ERROR]
* xref:develop:api/reference/errors/unauthorized_object.adoc[Unauthorized Object Error - UNAUTHORIZED_OBJECT_ERROR]
