# frozen_string_literal: true
require "decidim/common_rake"

desc "Build webpack bundle file"
task "webpack:build" do
  sh "yarn build:prod"
end

Rake::Task[:release].clear
desc "Override release task"
task "release", [:remote] => ["build", "webpack:build", "release:guard_clean",
                              "release:source_control_push", "release:rubygem_push"] do
end

Rake::Task[:build].enhance ['webpack:build']