require:
  - decidim/dev/rubocop/cop/decidim/message_antipattern
  - decidim/dev/rubocop/cop/decidim/enforce_permission_to
  - decidim/dev/rubocop/cop/decidim/organization_scoped_finder
  - decidim/dev/rubocop/cop/decidim/rspec/memoized_name

Decidim/MessageAntipattern:
  Enabled: true
  Include:
    - "**/spec/**/*"
    - "**/test/**/*"

Decidim/EnforcePermissionTo:
  Enabled: true
  Severity: warning
  Include:
    - "**/app/controllers/**/*.rb"
  AuthorizedBaseClasses:
    - "Decidim::Components::BaseController"
    - "Decidim::Accountability::ApplicationController"
    - "Decidim::Blogs::ApplicationController"
    - "Decidim::Budgets::ApplicationController"
    - "Decidim::CollaborativeTexts::ApplicationController"
    - "Decidim::Debates::ApplicationController"
    - "Decidim::Elections::ApplicationController"
    - "Decidim::Meetings::ApplicationController"
    - "Decidim::Pages::ApplicationController"
    - "Decidim::Proposals::ApplicationController"
    - "Decidim::Surveys::ApplicationController"
    - "Decidim::Templates::ApplicationController"
  AuthorizedBaseActions:
    - "index"
    - "show"
    - "home"
  Exclude:
    - "**/decidim-system/**/*.rb"
    - "**/app/controllers/decidim/errors_controller.rb"
    - "**/app/controllers/decidim/homepage_controller.rb"
    - "**/app/controllers/decidim/manifests_controller.rb"
    - "**/app/controllers/decidim/favicon_controller.rb"
    - "**/app/controllers/decidim/static_map_controller.rb"
    - "**/app/controllers/decidim/short_links_controller.rb"
    - "**/app/controllers/decidim/open_data_controller.rb"
    - "**/app/controllers/decidim/timeouts_controller.rb"
    - "**/app/controllers/decidim/upload_validations_controller.rb"
    - "**/app/controllers/decidim/doorkeeper/**/*.rb"
    - "**/app/controllers/decidim/authorization_modals_controller.rb"
    - "**/app/controllers/decidim/free_resource_authorization_modals_controller.rb"
    - "**/app/controllers/decidim/gamification/**/*.rb"
    - "**/app/controllers/decidim/user_activities_controller.rb"
    - "**/app/controllers/decidim/newsletters_controller.rb"
    - "**/app/controllers/decidim/resource_autocomplete_controller.rb"
    - "**/app/controllers/decidim/searches_controller.rb"
    - "**/app/controllers/decidim/links_controller.rb"
    - "**/app/controllers/decidim/private_downloads_controller.rb"
    - "**/app/controllers/decidim/qr_controller.rb"
    - "**/decidim-design/**/*.rb"
    - "**/decidim-dev/**/*.rb"
    - "**/decidim-api/**/*.rb"
    - "**/app/controllers/decidim/devise/**/*.rb"
    - "**/app/controllers/decidim/profiles_controller.rb"
    - "**/app/controllers/decidim/offline_controller.rb"
    - "**/app/controllers/decidim/demographics/demographics_controller.rb"
    - "**/app/controllers/decidim/initiatives/authorization_create_modals_controller.rb"
    - "**/app/controllers/decidim/initiatives/authorization_sign_modals_controller.rb"
    - "**/app/controllers/decidim/initiatives/create_initiative_controller.rb"
    - "**/app/controllers/decidim/meetings/directory/meetings_controller.rb"
    - "**/app/controllers/decidim/verifications/authorizations_controller.rb"
    - "**/app/controllers/decidim/forms/concerns/has_questionnaire.rb"
    - "**/app/controllers/concerns/decidim/resource_versions_concern.rb"

Decidim/RSpec/MemoizedName:
  Enabled: true
  Include:
    - "**/spec/system/**/*"
    - "**/spec/shared/**/*"

Decidim/OrganizationScopedFinder:
  Enabled: true
  Severity: warning
  Include:
    - "**/app/controllers/**/admin/**/*.rb"
  Exclude:
    - "**/decidim-system/**/*.rb"
