require:
  - decidim/dev/rubocop/cop/decidim/message_antipattern
  - decidim/dev/rubocop/cop/decidim/enforce_permission_to
  - decidim/dev/rubocop/cop/decidim/rspec/memoized_name

Decidim/MessageAntipattern:
  Enabled: true
  Include:
    - "**/spec/**/*"
    - "**/test/**/*"

Decidim/EnforcePermissionTo:
  Enabled: true
  Severity: warning
  Include:
    - "**/app/controllers/**/admin/*.rb"
  Exclude:
    - "**/decidim-system/**/*.rb"

Decidim/RSpec/MemoizedName:
  Enabled: true
  Include:
    - "**/spec/system/**/*"
    - "**/spec/shared/**/*"
