= Configuring

Decidim is a Ruby on Rails library, and as such we try to follow their conventions. Please read https://guides.rubyonrails.org/configuring.html[Configuring Rails Applications].

Decidim is also a command line executable capable of generating your own Decidim installation.

Install it as:

[source,console]
----
gem install decidim
----

For a simple, bare application, just run:

[source,console]
----
decidim my_decidim_application
----

However you can take advantage of the optional flags to automatically configure some aspects of the application.
Check the available options using the `--help` modifier:

[source,console]
----
decidim --help
----

For instance, if you are planing to use some external cloud storage service (such as S3), create a Decidim application using the `--storage` modifier:

[source,console]
----
decidim --storage s3 my_decidim_application
----

It is also recommended to use a proper Job Queue processor such as `sidekiq` or `delayed_job`. The `--queue` modifier allows you to generate a Decidim Application with a proper Sidekiq configuration (DelayedJob is not supported yet, PR welcomed, but you can easily just follow the https://github.com/collectiveidea/delayed_job[official instructions]):

[source,console]
----
decidim --queue sidekiq my_decidim_application
----

Then make use of the related xref:configure:environment_variables.adoc[Environment Variables] to configure your particular provider.

Just as a reminder, these files are important:

* config/database.yml

Although most of these settings you can change them through xref:configure:environment_variables.adoc[Environment Variables].

You also have more settings in:

* xref:configure:initializer.adoc[Decidim initializer file].
* xref:configure:environment_variables.adoc[Environment variables].
* xref:configure:system.adoc[System panel].
