name: Bug report
description: Create a report to help us improve
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: "When I go to …, I am not seeing the correct behavior for …"
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: |
        Steps to reproduce the behavior.

        Example:
        1. Go to admin -> settings
        2. Click on "Appearance"
        3. Scroll down to organization colors
        4. See error
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
  - type: textarea
    id: stacktrace
    attributes:
      label: Stacktrace
      description: If applicable, add the error stacktrace to help explain your problem.
  - type: textarea
    id: extra
    attributes:
      label: Extra data
      description: |
        Please complete the following information to describe your environment.

        Example:
        - Device: Desktop
        - Device OS: Windows 11
        - Browser: Chrome
        - Decidim Version: 0.10
        - Decidim installation: Metadecidim
      value: |
        - Device:
        - Device OS:
        - Browser:
        - Decidim Version:
        - Decidim installation:
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here. For instance, add Metadecidim link.
