#!/usr/bin/env ruby
# frozen_string_literal: true

if File.exist?(File.expand_path("../../.git", __dir__))
  ENV["RUBYOPT"] = ENV["RUBYOPT"].sub("-rsimplecov ", "")
  ENV["RUBYLIB"] = ENV["RUBYLIB"].sub("#{File.expand_path("..", __dir__)}/lib:", "")

  gem "decidim-core"
end

if ARGV[0] == "--component"
  ARGV.replace(["component", *ARGV[1..-1]])

  require "decidim/generators/component_generator"

  Decidim::Generators::ComponentGenerator.start
else
  require "decidim/generators/app_generator"

  Decidim::Generators::AppGenerator.start
end
