# frozen_string_literal: true

require "decidim/api/test/component_context"
require "decidim/api/test/shared_examples/amendable_interface_examples"
require "decidim/api/test/shared_examples/amendable_proposals_interface_examples"
require "decidim/api/test/shared_examples/attachable_interface_examples"
require "decidim/api/test/shared_examples/authorable_interface_examples"
require "decidim/api/test/shared_examples/categories_container_examples"
require "decidim/api/test/shared_examples/categorizable_interface_examples"
require "decidim/api/test/shared_examples/coauthorable_interface_examples"
require "decidim/api/test/shared_examples/commentable_interface_examples"
require "decidim/api/test/shared_examples/fingerprintable_interface_examples"
require "decidim/api/test/shared_examples/followable_interface_examples"
require "decidim/api/test/shared_examples/input_filter_examples"
require "decidim/api/test/shared_examples/input_sort_examples"
require "decidim/api/test/shared_examples/likeable_interface_examples"
require "decidim/api/test/shared_examples/localizable_interface_examples"
require "decidim/api/test/shared_examples/participatory_space_resourcable_interface_examples"
require "decidim/api/test/shared_examples/referable_interface_examples"
require "decidim/api/test/shared_examples/scopable_interface_examples"
require "decidim/api/test/shared_examples/statistics_examples"
require "decidim/api/test/shared_examples/taxonomizable_interface_examples"
require "decidim/api/test/shared_examples/timestamps_interface_examples"
require "decidim/api/test/shared_examples/traceable_interface_examples"
require "decidim/api/test/type_context"
