# frozen_string_literal: true

require "bundler/gem_tasks"
require "rspec/core/rake_task"
require_relative "../lib/decidim/gem_manager"

RSpec::Core::RakeTask.new(:spec)

task default: :spec

desc "Installs all gems locally."
task :install_all do
  Decidim::GemManager.run_all(
    "gem build %name && mv %name-%version.gem ..",
    include_root: false
  )

  Decidim::GemManager.new(File.expand_path("..", __dir__)).run(
    "gem build %name && gem install *.gem"
  )
end

desc "Uninstalls all gems locally."
task :uninstall_all do
  Decidim::GemManager.run_all(
    "gem uninstall %name -v %version --executables --force"
  )

  Decidim::GemManager.new(File.expand_path("..", __dir__)).run(
    "rm decidim-*.gem"
  )
end
