
version: "3"

services:
  rails:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: