require "decidim/extends/models/proposal_extend.rb"
require "decidim/extends/commands/vote_proposal_extend.rb"
require "decidim/extends/permissions/permissions_extend.rb"
require "decidim/extends/models/proposal_vote_extend.rb"
require "decidim/extends/create_proposal_extend.rb"