# frozen_string_literal: true
begin
  require "bundler/setup"
rescue LoadError
  puts "You must `gem install bundler` and `bundle install` to run rake tasks"
end

require_relative "../lib/common_rake"
require "rdoc/task"

RDoc::Task.new(:rdoc) do |rdoc|
  rdoc.rdoc_dir = "rdoc"
  rdoc.title    = "Decidim::Core"
  rdoc.options << "--line-numbers"
  rdoc.rdoc_files.include("README.md")
  rdoc.rdoc_files.include("lib/**/*.rb")
end

load "rails/tasks/statistics.rake"

require "bundler/gem_tasks"

task default: :test

desc "Generates a dummy app for testing"
task :test_app do
  ENV["ENGINE_PATH"] = File.dirname(__FILE__)
  Rake::Task["common:test_app"].invoke
end

task test: :test_app do
  Dir.chdir(File.dirname(__FILE__).to_s) do
    sh "rspec spec"
  end
end
