= Cookies

With cookie consent we can explain better what cookies do we use, why we're using these cookies, and let the user choose which cookies they want to use.

== Different cookie categories available in Decidim

By default there are four (4) cookie categories: **essential**, **preferences**, **analytics** and **marketing**. To display embedded iframes properly user has to give consent to all categories.

== Adding scripts which require cookie consent

The recommended place for scripts is ```app/views/layouts/decidim/_head_extra.html.erb```.
For example, if you want to add a script that requires marketing consent, you can add the following code:

[source,javascript]
----
<script type="text/plain" data-consent="marketing">
  console.log('marketing cookies accepted');
</script>
----

NOTE: Script type should be "text/plain". Without that, user's cookie consent setting doesn't affect.

== Adding cookie category and cookie documentation

You are able to modify cookie categories via the `consent_gategories` configuration option.

For example if you want to add a "statistics" category you need to add following code to your app's initializer:

[source,ruby]
----
Decidim.configure do |config|
  config.consent_categories = [
    {
      slug: "essential",
      mandatory: true,
      cookies: [
        {
          type: "cookie",
          name: "_session_id"
        },
        {
          type: "cookie",
          name: Decidim.consent_cookie_name
        }
      ]
    },
    {
      slug: "preferences",
      mandatory: false
    },
    {
      slug: "analytics",
      mandatory: false
    },
    {
      slug: "marketing",
      mandatory: false
    },
    {
      slug: "statistics",
      mandatory: false,
      cookies: [
        type: "cookie",
        name: "statistics-cookie"
      ]
    }
  ]
end
----

When adding cookie categories and cookies also remember to add the following xref:admin:texts.adoc[translations]:

For category:

[listing]
----
layouts.decidim.data_consent.modal.statistics.title
layouts.decidim.data_consent.modal.statistics.description
----

For cookie:

[listing]
----
layouts.decidim.data_consent.details.cookies.statistics-cookie.description
layouts.decidim.data_consent.details.cookies.statistics-cookie.service
----

* Description explains the purpose of using this cookie
* Service explains the 3rd party service where this cookie is coming from

So, for instance for the English language (`en`), it would look like this:

[source,yaml]
----
en:
  layouts:
    decidim:
      data_consent:
        modal:
          statistics:
            title: The title for the statistics
            description: The description for the statistics
        details:
          cookies:
            statistics-cookie:
              description: The purpose of the cookie
              service: The 3rd party service of the cookie
----
