name: '[CI] Module rspec'
description: 'Test module with rspec'
inputs:
  name:
    description: 'Module Name'
    required: true
  github_token:
    description: 'Github token'
    required: true
  ruby_version:
    description: 'Ruby Version'
    default: "3.1.1"
    required: false
  node_version:
    description: 'Node version'
    default: '16.13.0'
    required: false
  processor_count:
    description: "Number or parallel jobs to run"
    default: "4"
    required: false

runs:
  using: "composite"
  steps:
    - name: Get npm cache directory path
      id: npm-cache-dir-path
      run: echo "dir=$(npm get cache)-${{ inputs.name }}" >> $GITHUB_OUTPUT
      shell: "bash"
    - uses: actions/cache@v3
      id: npm-cache
      with:
        path: ${{ steps.npm-cache-dir-path.outputs.dir }}
        key: npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          npm-
    - run: bundle exec rake test_app
      name: Create test app
      shell: "bash"
    - run: bundle exec rake parallel:create parallel:migrate
      name: Parallel tests
      shell: "bash"
      working-directory: ./spec/decidim_dummy_app/
      env:
        PARALLEL_TEST_PROCESSORS: " ${{ inputs.processor_count }}"
