#!/bin/bash

fail_fast=${FAIL_FAST:-false}
simplecov=${SIMPLECOV:-true}

args=("$@")

printf -v cmd '%q ' "${args[@]}"

docker-compose run --rm -e "FAIL_FAST=$fail_fast" -e "SIMPLECOV=$simplecov" decidim bash -c "bin/rspec $cmd"
