= Endorsable

== Things can be endorsable

`Endorsable` is a feature to allow participants to promote (reivindicate, etc.) resources in the platform to their followers.

When endorsing an element the endorsements counter for this element is increased and a notification to all the followers of the participant is sent.

Participants can endorse with their own identity. Each endorsing identity on its own will increment the endorsements counter by one.

== Data model

A `decidim_endorsements` table registers each endorsement that each identity gives to each element. This is, one endorsable has many endorsements, and each endorsement belongs to one endorsable.
For performance, an endorsable has a counter cache of endorsements.

[source,ascii]
----
+----------------------+
|  Decidim::Endorsable |
|   ((Proposal,...))   |
+----------------------+  0..N +--------------------+
|-has_many endorsements|-------+Decidim::Endorsement|
|#counter cache column |       +--------------------+   +-------------+
|-endorsements_counter |       |-author: a user     |<--+Decidim::User|
+----------------------+       +--------------------+   +-------------+

Thus, each endorsable must have the endorsements counter cache column.
This is an example migration to add the endorsements counter cache column to a resource:

[source,ruby]
----
class AddEndorsementsCounterCacheToProposals < ActiveRecord::Migration[5.2]
  def change
    add_column :decidim_proposals_proposals, :endorsements_count, :integer, null: false, default: 0
  end
end
----

== Administration Panel

It is a good practice to give the opportunity to the admin to switch Endorsements on and off.

There are two switches that are normally defined in the manifest of the element in the following way (usually this would be at component.rb in a Decidim engine):

[source,ruby]
----
    settings.attribute :endorsements_enabled, type: :boolean, default: true
    settings.attribute :endorsements_blocked, type: :boolean
----

* `endorsements_enabled`: when enabled endorsement functionality appears in the public views, when disabled, this functionality is hidden.
* `endorsements_blocked`: when blocked, the counter of endorsements is visible but no more endorsements can be added or withdrawn, the button is hidden.

== Permissions

In some cases, it may be interesting to require the user to be verified in order to be able to endorse. To do so, add the endorse action to the component manifest:

[source,ruby]
----
  component.actions = %w(endorse vote create withdraw amend)
----

Given that some settings have been defined in the Administration Panel, for the user to have permissions to endorse endorsements should be enabled and not blocked.

== Public view

=== The "Endorse" buttons cell

It normally appears in the resource detail view (show), at the bottom of the resource content, but above the comments when comments are enabled.
It allows users to endorse with any of their personal identity.
It also shows the current number of endorsements for this resource.

To render this button, `decidim-core` offers the `decidim/endorsement_buttons` cell. It is strongly recommended to use this cell to make new resources endorsable.

[source,ruby]
----
cell("decidim/endorsement_buttons", resource)
----

This cell will render the endorsement buttons depending on whether user endorsed the resource or not. The endorsements are labeled as *Likes*.

[source,ruby]
----
# By default the `show` method is invoked as usual
# Renders `render_endorsements_count` and `render_endorsements_button` in a block.
#
# It takes into account:
# - if endorsements are enabled
# - if users are logged in
# - if users require verification
 #
cell("decidim/endorsement_buttons", resource)
----

=== The list of endorsers

The `Decidim::EndorsersListCell` renders the list of endorsers of a resource. It is usually rendered in the show page of the resource, just upside the comments. Additionally, this cell also renders the pop-up required to view the endorsers of a certain resource.

[source,ruby]
----
# to render the list of endorsers, the cell requires the endorsable resource, and the current user
cell "decidim/endorsers_list", resource
# or using the helper
endorsers_list_cell(resource)
----
