= Conventions

TIP: These commands are available in Decidim 0.31.0, but you should really start to use it in Decidim 0.33.

As the need to migrate data increased, we need a more reliable way to migrate data. We have introduced data migrations, which are similar to schema migrations but they are run only when the database schema is up to date.

To run the data migrations, run the following command:

```console
bin/rails data:migrate:up
```

To see the status of available data migrations, run the following command:

```console
bin/rails data:migrate:status
```

#### 2.3.1. Developer notes

As you may need to run data migrations in your developed plugins, you can hook up to the data migration system by adding the following line to your gem's `engine.rb` file:

```ruby
 initializer "your_gem_name.data_migrate", after: "decidim_core.data_migrate" do
    DataMigrate.configure do |config|
      config.data_migrations_path << root.join("db/data").to_s
    end
  end
```

The migration files should be named following the pattern `YYYYMMDDHHMMSS_your_migration_name.rb`, and should be placed in the `db/data` folder. The structure of the migration should be something like:

```ruby
# frozen_string_literal: true

class YourMigrationName < ActiveRecord::Migration[7.2]

  # your custom classes should be defined here

  def up
    # your migration code
  end

  def down
    raise ActiveRecord::IrreversibleMigration
  end
end
```

You can read more about this change on PR [#15501](https://github.com/decidim/decidim/pull/15501).
