= Share tokens

Share tokens can be assigned to any model to provide a system to share unpublished resources with expirable and manageable tokens.

A share token is created by a user with an expiration time, and can be added as a query param to access otherwise restricted locations.

== Add share tokens to a model

The model must `include Decidim::ShareableWithToken` and implement `shareable_url(share_token)`, which should return the public url for the resource you want to share, including the token as a query parameter.

[source,ruby]
----
# Public: Public URL for your_resource with given share token as query parameter
def shareable_url(share_token)
  your_resource_public_url(self, share_token: share_token.token)
end
----

== Set permissions

You should change permissions logic for the resource to check if there is a `share_token` query parameter in the request url, and call `Decidim::ShareToken.use!` to both check if the token is valid, and if it is, to _use it_ (which increments `times_used` variable and sets `last_used_at` to current time).

It should do something similar to this:

[source,ruby]
----
token = context[:share_token]

return unless token.present?

allow! if Decidim::ShareToken.use!(token_for: your_resource, token: token)
----

== Manage tokens

Tokens can be managed in the components view similar as other resources (with and action icon like permissions for instance). By default, assemblies, conferences and participatory spaces are configured to have share tokens.

In order to implement it in other participatory spaces, you should:

1. Add the `share_tokens` CRUD routes in your `admin_engine.rb` file:

[source,ruby]
----
  resources :components do
    ...
    resources :share_tokens, except: [:show]
    ...
----

2. Add the controller for the participatory space, it only requires to inherit from `Decidim::Admin::ShareTokensController`:

[source,ruby]
----
# frozen_string_literal: true

module Decidim
  module Assemblies
    module Admin
      # This controller allows sharing unpublished things.
      # It is targeted for customizations for sharing unpublished things that lives under
      # an assembly.
      class ShareTokensController < Decidim::Admin::ShareTokensController
        include Concerns::AssemblyAdmin
      end
    end
  end
end
----
