Style/OpenStructUse:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

RSpec/VerifiedDoubleReference:
  Enabled: false

FactoryBot/ConsistentParenthesesStyle:
  Enabled: false

FactoryBot/ExcessiveCreateList:
  Enabled: false

RSpec/ExampleWording:
  Enabled: false

Rails/PluckInWhere:
  Enabled: false

RSpec/ReceiveMessages:
  Enabled: false

RSpecRails/NegationBeValid:
  Enabled: false

RSpec/MetadataStyle:
  Enabled: false

FactoryBot/FactoryAssociationWithStrategy:
  Enabled: false

RSpec/RemoveConst:
  Enabled: false

FactoryBot/AssociationStyle:
  Enabled: false

Rubycw/Rubycw:
  Enabled: false

Lint/SymbolConversion:
  Enabled: false

Style/RedundantParentheses:
  Enabled: false

Style/MapIntoArray:
  Enabled: false




Style/ArgumentsForwarding:
  Enabled: false

Style/SuperArguments:
  Enabled: false

Lint/SelfAssignment:
  Enabled: false

Style/SendWithLiteralMethodName:
  Enabled: false

Rails/WhereRange:
  Enabled: false
