base_locale: en
ignore_unused:
- "decidim.features.meetings.name"
- "decidim.features.meetings.settings.*"
- "activemodel.attributes.*"
- "decidim.resource_links.*"
ignore_missing:
  - decidim.scopes.global
search:
  strict: false
