name: "Pull Request Labeler"
on:
  pull_request_target:
    branches-ignore:
      - "chore/l10n*"
    types: [ opened, edited, synchronize, reopened, labeled, unlabeled ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/labeler@v5
        with:
          dot: 'true'
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
