name: "[CI] Generators (Main)"
on:
  push:
    branches:
      - develop
      - release/*
      - "*-stable"
  pull_request:
    branches-ignore:
      - "chore/l10n*"
    paths:
      - "*"
      - ".github/**"
      - "decidim-core/**"
      - "decidim-generators/**"

env:
  CI: "true"
  RUBY_VERSION: 3.1.1
  NODE_VERSION: 16.9.1
  DECIDIM_MODULE: decidim-generators
  PARALLEL_TEST_PROCESSORS: 2

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  main:
    name: Tests
    runs-on: ubuntu-20.04
    if: "!startsWith(github.head_ref, 'chore/l10n')"
    timeout-minutes: 60
    services:
      postgres:
        image: postgres:11
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
    env:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost
      RUBYOPT: '-W:no-deprecated'
    steps:
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Get npm cache directory path
        id: npm-cache-dir-path
        run: echo "::set-output name=dir::$(npm get cache)-${{ env.DECIDIM_MODULE }}"
      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir-path.outputs.dir }}
          key: npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-
      - run: bundle install --jobs 4 --retry 3
        name: Install Ruby deps
        working-directory: ${{ env.DECIDIM_MODULE }}
      - run: bundle exec brakeman --rails6 --force-scan .
        name: Scanning Security issues on module
        working-directory: ${{ env.DECIDIM_MODULE }}
      - run: bundle exec rake parallel:spec['spec/lib/']
        name: RSpec
        working-directory: ${{ env.DECIDIM_MODULE }}
        env:
          SIMPLECOV: "true"
      - run: ./.github/upload_coverage.sh $DECIDIM_MODULE $GITHUB_EVENT_PATH
        name: Upload coverage
