name: "[CI] Proposals (system admin)"
on:
  push:
    branches:
      - develop
      - release/*
      - "*-stable"
  pull_request:
    branches-ignore:
      - "chore/l10n*"
    paths:
      - "*"
      - ".github/**"
      - "decidim-admin/**"
      - "decidim-assemblies/**"
      - "decidim-budgets/**"
      - "decidim-comments/**"
      - "decidim-core/**"
      - "decidim-dev/**"
      - "decidim-meetings/**"
      - "decidim-participatory_processes/**"
      - "decidim-proposals/**"

env:
  CI: "true"
  RUBY_VERSION: 3.1.1
  NODE_VERSION: 16.13.0
  DECIDIM_MODULE: decidim-proposals
  PARALLEL_TEST_PROCESSORS: 2
  CODECOV_TOKEN: bc15b944-6b42-420a-b3f9-a5a8fb214326
  WEBPACKER_RUNTIME_COMPILE: "false"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_app:
    uses: ./.github/workflows/build_app.yml
    secrets: inherit
    name: Build test application

  main:
    strategy:
      matrix:
        test-command:
          - bundle exec parallel_test --type rspec --pattern spec/ --exclude-pattern spec/system
          - bundle exec parallel_test --type rspec --pattern spec/system --exclude-pattern spec/system/admin
          - bundle exec parallel_test --type rspec --pattern spec/system/admin
    needs: build_app
    name: Tests
    uses: ./.github/workflows/test_app.yml
    secrets: inherit
    with:
      working-directory: "decidim-proposals"
      test_command: ${{ matrix.test-command }}


