name: "[CI] Proposals (system public 1)"
on:
  push:
    branches:
      - develop
      - release/*
      - "*-stable"
  pull_request:
    branches-ignore:
      - "chore/l10n*"
    paths:
      - "*"
      - ".github/**"
      - "decidim-admin/**"
      - "decidim-assemblies/**"
      - "decidim-budgets/**"
      - "decidim-comments/**"
      - "decidim-core/**"
      - "decidim-dev/**"
      - "decidim-meetings/**"
      - "decidim-participatory_processes/**"
      - "decidim-proposals/**"

env:
  CI: "true"
  RUBY_VERSION: 2.7.5
  NODE_VERSION: 16.9.1
  DECIDIM_MODULE: decidim-proposals

jobs:
  main:
    name: Tests
    runs-on: ubuntu-20.04
    if: "!startsWith(github.head_ref, 'chore/l10n')"
    timeout-minutes: 60
    services:
      postgres:
        image: postgres:11
        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: postgres
      validator:
        image: ghcr.io/validator/validator:latest
        ports: ["8888:8888"]
    env:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: localhost
      RUBYOPT: '-W:no-deprecated'
      VALIDATOR_HTML_URI: http://localhost:8888/
    steps:
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 1
      - uses: ./.github/actions/module-rspec
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          name: ${{ env.DECIDIM_MODULE }}
      - run: |
          count=$(ls spec/system/*_spec.rb | wc -l | tr -d ' ')
          half=$(expr $count / 2)
          list_of_files=$(ls spec/system/*_spec.rb | sed -n "1,$(echo $half)p" | xargs)
          bundle exec rspec $list_of_files
        name: RSpec
        working-directory: ${{ env.DECIDIM_MODULE }}
        env:
          SIMPLECOV: "true"
      - run: ./.github/upload_coverage.sh decidim-proposals-system-public $GITHUB_EVENT_PATH
        name: Upload coverage
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: screenshots
          path: ./spec/decidim_dummy_app/tmp/screenshots
          if-no-files-found: ignore
