name: "[CI] Security"
on:
  push:
    branches:
      - develop
      - master
      - release/*
      - "*-stable"
  pull_request:
    branches-ignore:
      - "chore/l10n*"

env:
  CI: "true"
  SIMPLECOV: "false"
  RUBY_VERSION: 2.7.1

jobs:
  lint:
    name: Code Security
    runs-on: ubuntu-latest
    if: "!startsWith(github.head_ref, 'chore/l10n')"
    steps:
      - uses: rokroskar/workflow-run-cleanup-action@v0.2.2
        if: "github.ref != 'refs/heads/master' || github.ref != 'refs/heads/develop'"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      - uses: actions/checkout@v2.0.0
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VERSION }}
          bundler-cache: true
      - run: bundle exec brakeman --rails6 --force-scan
        name: Scanning Security issues on Main
      - run: bundle exec brakeman --rails6 --force-scan decidim-dev --skip-files decidim-dev/lib/decidim/dev/test/*
        name: Scanning Security issues on Dev module
