name: publiccode.yml validation

on: [pull_request, push]
permissions:
  contents: read
jobs:
  publiccode_yml_validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install publiccode-parser
        run: curl -sSL https://github.com/italia/publiccode-parser-go/releases/latest/download/publiccode-parser-linux-amd64 -o publiccode-parser && chmod +x publiccode-parser
      - name: Validate publiccode.yml
        run: ./publiccode-parser --no-network publiccode.yml
