name: publiccode.yml validation

on: [pull_request, push]
permissions:
  contents: read
jobs:
  publiccode_yml_validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install publiccode-parser
        run: |
          curl -sSL https://github.com/italia/publiccode-parser-go/releases/latest/download/publiccode-parser-go_Linux_x86_64.tar.gz -o publiccode-parser.tar.gz
          tar -xzf publiccode-parser.tar.gz publiccode-parser-go
          chmod +x publiccode-parser-go
      - name: Validate publiccode.yml
        run: ./publiccode-parser-go --no-network publiccode.yml
